<?php

namespace Gdev\IsaacBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * SeedResponseRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeedResponseRepository extends EntityRepository
{
}
