services:
    gdev_user.registration.form.type:
        class: Gdev\UserBundle\Form\Type\RegistrationFormType
        arguments: [%fos_user.model.user.class%]
        tags:
            - { name: form.type, alias: gdev_user_registration }

    gdev_user.openid_user_manager:
        class: Gdev\UserBundle\Security\User\OpenIdUserManager
        # we used an EntityManager, so don't forget it in dependency injection
        # you may want to adapt it, only the IdentityManager is mandatory
        arguments: [@fp_openid.identity_manager, @doctrine.orm.entity_manager]